# Lambda Functions

GET https://9r1k47okme.execute-api.us-east-1.amazonaws.com/prod/spaces?id=9d2ff02a-19bd-4371-9e4d-f211cfe3c660
###

POST https://9r1k47okme.execute-api.us-east-1.amazonaws.com/prod/spaces
Content-Type: application/json

{
  "location": "New Mexico",
  "name": "My Space",
  "description": "This is my space"
}
###
PUT https://9r1k47okme.execute-api.us-east-1.amazonaws.com/prod/spaces?id=9d2ff02a-19bd-4371-9e4d-f211cfe3c660
Content-Type: application/json

{
  "location": "South Briadway, Albuquerque, New Mexico",
  "name": "My Space",
  "description": "This is my space"
}
###